### ISSUE TITLE
Guide for using this? I have done all steps i have my bot ready

### ISSUE THREAD

**Issue by ProtoManGG** [alx-xlx/gdrive-clone#1]
But I still dont know how to use it can you help please ?

I used Gcopy.sh with sudo permissions still i got the error:

![image](https://user-images.githubusercontent.com/52622543/102779813-e206b300-43ba-11eb-8220-a39451c91d69.png)

**Comment by alx-xlx** [comment]
Line 49 of `gcopy.sh` has some permission issue
```
${REPOPATH}/gclone copy gc:{`echo $SOURCE | sed 's/.*folders\///'`} gc:{$DESTINATION} --config=${REPOPATH}/rc.conf --transfers 50 -v --stats-one-line -P --stats=15s --ignore-existing --drive-server-side-across-configs --drive-chunk-size 128M --drive-acknowledge-abuse --drive-keep-revision-forever
```
make sure `gclone` binary is executable
and try `gclone` manually

**Comment by xkoti** [comment]
@alx-xlx This project looks amazing but how to set this up properly? We need more detailed instruction.

Thanks

**Comment by ZeusCraft10** [comment]
> 

brooo.. you are supposed to do all the linux setup in the google cloud console. This should be on the cloud server that is running linux. ALl transfers should be done from there, not from WSL.
